### ISSUE TITLE
Spotify Part of the README

### ISSUE THREAD

**Issue by alrafiabdullah** [staciax/staciax#1]
Hi,
How did you get the _uid_ of Spotify? I have the developer console but can't use it. Can you help? Thank you.

**Comment by staciax** [comment]
![image](https://user-images.githubusercontent.com/69411527/196181539-2ac38277-6e96-4055-bdf4-2c40ae1d986f.png)
https://github.com/kittinan/spotify-github-profile

**Comment by alrafiabdullah** [comment]
It worked! Now I have a cool Spotify badge. Thank you!
